### ISSUE TITLE
Update fails if the previous version was using CDS view Entities not CDS Views

### ISSUE THREAD

**Issue by fidley** [DevEpos/abap-search-tools#25]
Hi @stockbal , 
I wanted to update the repository, but it fails to activate the CDS views. 
![image](https://github.com/DevEpos/abap-search-tools/assets/7912195/c7f22b89-a7a8-4e2c-8e0f-a7f0f891770c)
I've compared the versions and I had the CDS entities before now, in main branch there are CDS views. I guess I had before the branch for NW 7.55. 

I guess this is nothing we can deal with?

**Comment by stockbal** [comment]
Hi @fidley,

sorry for inconvenience. There was a short period where I switched to CDS view entities. But then I had issues because UNION and DISTINCT are not available in the view entities on NW 7.55. As did not want to create yet another branch I decided to revert the changes (6b28b3a842d3ac1d9acb146bb9d7c2e30a02e077) and stay with the old CDS views.

Unfortunately the system does not allow to convert CDS view entities back to the old DDIC based CDS views, so you either need to uninstall the repository and reinstall it, or you can try to just delete all the CDS views in the repo and perform a pull afterwards.

Best regards,
Ludwig

**Comment by stockbal** [comment]
It just came to me that I even made a note for just such an installation issue 😅. https://github.com/DevEpos/abap-search-tools/wiki/Installation-Issues. It is linked from the README in the main branch.

**Comment by fidley** [comment]
Thanks! I'll try that!
