### ISSUE TITLE
Search filter "FIELD: " not returning all values

### ISSUE THREAD

**Issue by therealsimwoe** [DevEpos/abap-search-tools#31]
Currently I'll face the issue that in a S/4HANA OnPrem 2022 FPS02 system when I search with the filter value "field:" the result set is not complete.

For example when a search with the following filter is executed: **field: vegr3** the CDS-View: **I_HandlingUnitHeader** is not in the result set. Despite the fact this view is using the field:
vegr3                                             as HandlingUnitGroup3,

Is this a bug within the search?

Thank you very much for your support on this!

**Comment by stockbal** [comment]
Hi @therealsimwoe,

The alias information is currently not stored in a database table I know, so I cannot easily access both values, otherwise I would do it. Without looking into it if it may be possible with a recursive approach as well you currently can use a 2-step approach to get to the result you want:

1. Run an ABAP Object Search with type "Database Table" and query `field : vegr3`. In its result there should be an entry for table ` VEKP`.
2. Run a Field Analysis wia the context menu of `VEKP`. In the _CDS Analyzer_ view you then have the possibility to show all usages of the field `VEGR3`
![image](https://github.com/DevEpos/abap-search-tools/assets/35834861/087195a7-472a-4547-8478-290bc487b9be)
 
I hope this helps.

Kind regards,
Ludwig

**Comment by therealsimwoe** [comment]
Hi Ludwig,

thank you very much for the feedback. I tested the recommended two step-approach and it works as expected. This already helps a lot in daily operations. And together with the Recursive Feature from it will be even further improved to find a released view with a certain field https://github.com/DevEpos/abap-search-tools/issues/32 . But it is really unfortunate that the alias info can't be read from the DB. 

Thank you again for your help and the great tool.
